In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

print("Environment ready!")

Pandas version: 2.2.3
NumPy version: 2.1.3
Environment ready!

In [2]:
from google.colab import files

uploaded = files.upload()

Saving WA_Fn-UseC_-Telco-Customer-Churn.csv to WA_Fn-UseC_-Telco-Customer-Churn.csv

In [3]:
file_name = next(iter(uploaded))

df = pd.read_csv(file_name)

print("Dataset loaded successfully!")
print("Shape:", df.shape)
print("\nFirst 5 rows:")
display(df.head())

Dataset loaded successfully!
Shape: (7043, 21)

First 5 rows:

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
print("Column names:")
print(df.columns.tolist())

print("\nData types and non-null counts:")
df.info()

Column names:
['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

Data types and non-null counts:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [5]:
print("Missing values per column:")
print(df.isnull().sum())

print("\nTotal duplicate rows:", df.duplicated().sum())

Missing values per column:
customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

Total duplicate rows: 0

In [6]:
import os

file_size_bytes = os.path.getsize(file_name)
file_size_kb = file_size_bytes / 1024

print("File name:", file_name)
print("File size:", round(file_size_kb, 2), "KB")

File name: WA_Fn-UseC_-Telco-Customer-Churn.csv
File size: 954.59 KB

In [7]:
excel_file = "customer_churn.xlsx"

df.to_excel(excel_file, index=False)

print("Excel file created:", excel_file)

Excel file created: customer_churn.xlsx

In [8]:
df_excel = pd.read_excel(excel_file)

print("Excel data shape:", df_excel.shape)
print("\nFirst 5 rows from Excel:")
display(df_excel.head())

Excel data shape: (7043, 21)

First 5 rows from Excel:

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [9]:
json_file = "customer_churn.json"

df.to_json(json_file, orient="records", indent=2)

print("JSON file created:", json_file)

JSON file created: customer_churn.json

In [10]:
df_json = pd.read_json(json_file, orient="records")

print("JSON data shape:", df_json.shape)
print("\nFirst 5 rows from JSON:")
display(df_json.head())

JSON data shape: (7043, 21)

First 5 rows from JSON:

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [11]:
parquet_file = "customer_churn.parquet"

df.to_parquet(parquet_file, index=False)

print("Parquet file created:", parquet_file)

Parquet file created: customer_churn.parquet

In [12]:
df_parquet = pd.read_parquet(parquet_file)

print("Parquet data shape:", df_parquet.shape)
print("\nFirst 5 rows from Parquet:")
display(df_parquet.head())

Parquet data shape: (7043, 21)

First 5 rows from Parquet:

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [13]:
import os
import pandas as pd

files_to_compare = {
    "CSV": file_name,
    "Excel": excel_file,
    "JSON": json_file,
    "Parquet": parquet_file
}

size_results = []

for format_name, path in files_to_compare.items():
    size_kb = os.path.getsize(path) / 1024
    size_results.append({
        "Format": format_name,
        "Size (KB)": round(size_kb, 2)
    })

size_df = pd.DataFrame(size_results)

display(size_df.sort_values("Size (KB)"))

    Format  Size (KB)
3  Parquet     195.90
1    Excel     629.13
0      CSV     954.59
2     JSON    4050.17

In [14]:
import time

load_times = []

for format_name, path in files_to_compare.items():

    start_time = time.perf_counter()

    if format_name == "CSV":
        temp_df = pd.read_csv(path)
    elif format_name == "Excel":
        temp_df = pd.read_excel(path)
    elif format_name == "JSON":
        temp_df = pd.read_json(path, orient="records")
    elif format_name == "Parquet":
        temp_df = pd.read_parquet(path)

    elapsed_time = time.perf_counter() - start_time

    load_times.append({
        "Format": format_name,
        "Load time (seconds)": round(elapsed_time, 5)
    })

load_time_df = pd.DataFrame(load_times)

display(load_time_df.sort_values("Load time (seconds)"))

# "In this block, I am measuring the time required to load the same dataset from four different file formats.
# I use Python's high-resolution performance timer to record the start and finish times of each read operation.
# Depending on the format, I call the appropriate Pandas reader. I calculate the elapsed time, store the result, and
# sort the results from fastest to slowest. This gives me an initial comparison of loading performance. However,
# I should repeat the test under controlled conditions before drawing a strong conclusion."

    Format  Load time (seconds)
3  Parquet              0.02434
0      CSV              0.03155
2     JSON              0.11005
1    Excel              3.28079

In [15]:
print("CSV vs Excel:", df.equals(df_excel))
print("CSV vs JSON:", df.equals(df_json))
print("CSV vs Parquet:", df.equals(df_parquet))

# "In this block, I am validating whether the dataset remains consistent after conversion into different file formats.
# I use the equals method to compare the original DataFrame with each converted DataFrame.
# This checks whether the values, column order, and data types match. If the result is true, the DataFrames are equal according to Pandas.
# If the result is false, I need to investigate whether the conversion changed a data type or a value.
# This validation is important because a file can be created successfully without guaranteeing that every detail was preserved."

CSV vs Excel: True
CSV vs JSON: True
CSV vs Parquet: True

In [16]:
format_summary = size_df.merge(
    load_time_df,
    on="Format"
)

display(format_summary.sort_values("Size (KB)"))

# "In this block, I am combining the file-size measurements and loading-time measurements into a single summary table.
# Both tables contain a common column called Format, so I use the merge method to join them using that column.
# Then, I sort the result by file size.
# This makes it easier to compare the storage and loading trade-offs together rather than looking at two separate tables.
# I can use this information, along with the format's capabilities and intended use, to make a more informed choice."

    Format  Size (KB)  Load time (seconds)
3  Parquet     195.90              0.02434
1    Excel     629.13              3.28079
0      CSV     954.59              0.03155
2     JSON    4050.17              0.11005

Data Formats

Format: Typical use

CSV:	Simple tabular data exchange

Excel:	Business reporting and spreadsheet workflows

JSON:	APIs and semi-structured data

Parquet:	Efficient analytical storage and column-oriented processing

We also measured file sizes, loading times, and data consistency.

Getting More Data

Our next question is:

Can additional data help us predict customer churn more effectively?

We should investigate this carefully. More rows do not automatically

mean a better model; the new data must be relevant, reliable, and

representative.

In [17]:
# Check the target distribution

print("Customer churn distribution:")
print(df["Churn"].value_counts())

print("\nCustomer churn percentage:")
print(
    (df["Churn"].value_counts(normalize=True) * 100).round(2)
)

Customer churn distribution:
Churn
No     5174
Yes    1869
Name: count, dtype: int64

Customer churn percentage:
Churn
No     73.46
Yes    26.54
Name: proportion, dtype: float64

In [18]:
# Explore customer characteristics

print("Tenure statistics by churn status:")

display(
    df.groupby("Churn")["tenure"]
      .describe()
      .round(2)
)

# "In this analysis, I compared customer tenure between customers who churned and those who stayed.
# The average tenure of customers who stayed is 37.57 months, whereas customers who churned have an average tenure of 17.98 months.
# The median values show a similar pattern: 38 months for customers who stayed and only 10 months for customers who churned.
# This suggests that customers with shorter tenure may be at greater risk of churn.
# However, this is an association rather than proof of causation.
#  I will investigate other customer characteristics before building the prediction model."

Tenure statistics by churn status:

        count   mean    std  min   25%   50%   75%   max
Churn
No     5174.0  37.57  24.11  0.0  15.0  38.0  61.0  72.0
Yes    1869.0  17.98  19.53  1.0   2.0  10.0  29.0  72.0

In [19]:
# Explore contract types

print("Customer count by contract and churn status:")

display(
    pd.crosstab(
        df["Contract"],
        df["Churn"],
        margins=True
    )
)

# In this block, I am analyzing the relationship between customer contract types and churn.

# First, I use the crosstab function from Pandas to create a frequency table. I compare three contract categories:
#  month-to-month, one-year, and two-year contracts, against the two churn outcomes: Yes and No.

# The margins argument adds totals for each row and column, which helps me understand the overall distribution.

# This analysis helps me investigate whether customers with different contract types show different churn patterns.
# For example, if month-to-month customers have a higher churn rate, the business could investigate retention strategies for that segment.

# However, these are descriptive statistics.
# I need to calculate churn percentages within each contract type before comparing their churn rates fairly.

Customer count by contract and churn status:

Churn             No   Yes   All
Contract
Month-to-month  2220  1655  3875
One year        1307   166  1473
Two year        1647    48  1695
All             5174  1869  7043

In [20]:
# Calculate churn rate programmatically
contract_churn_rate = pd.crosstab(
    df["Contract"],
    df["Churn"],
    normalize="index"
) * 100

display(contract_churn_rate.round(2))

# "In this block, I am calculating the churn percentage separately for each contract type.
# I use crosstab with normalize equal to index, which divides each cell by its row total.
# Multiplying by 100 converts the proportions into percentages.
# This makes it easier to compare churn rates fairly across contract categories,
# even though the categories contain different numbers of customers."

Churn              No    Yes
Contract
Month-to-month  57.29  42.71
One year        88.73  11.27
Two year        97.17   2.83

In [21]:
# Retrieve the dataset from JSONPlaceholder API

import requests

url = "https://jsonplaceholder.typicode.com/posts"

response = requests.get(url, timeout=30)

print("HTTP status code:", response.status_code)
print("Response type:", response.headers.get("Content-Type"))

# "In this block, I am connecting to an external API to retrieve data.
# First, I define the API endpoint URL.
# Then, I use the requests library to send an HTTP GET request, with a timeout to avoid waiting indefinitely.
# The response contains the server's reply.
#  I check the HTTP status code and content type to understand whether the request succeeded
#  and what kind of data the server returned. This is the first step in building an API-based data ingestion workflow."

HTTP status code: 200
Response type: application/json; charset=utf-8

In [22]:
api_data = response.json()

print("Number of records received:", len(api_data))
print("\nFirst two records:")
print(api_data[:2])


# "In this block, I am parsing the JSON data received from the API.
# I use the json method on the response object to convert the response body into Python objects.
# Then, I count the number of records returned and display the first two records.
# Inspecting a small sample helps me understand the structure and fields available before converting the data into a DataFrame."

Number of records received: 100

First two records:
[{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}, {'userId': 1, 'id': 2, 'title': 'qui est esse', 'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'}]

In [23]:
# Convert API data into a DataFrame

api_df = pd.DataFrame(api_data)

print("API DataFrame shape:", api_df.shape)
print("\nColumn names:")
print(api_df.columns.tolist())

display(api_df.head())

# "In this block, I am converting the API response into a Pandas DataFrame.
# The response is a list of Python dictionaries, where each dictionary represents one record.
# Pandas can convert this list into a tabular structure using the DataFrame constructor.
# I then inspect the shape, column names, and first five rows to understand the data.
# This makes the API response easier to analyze and prepares it for further data processing."

API DataFrame shape: (100, 4)

Column names:
['userId', 'id', 'title', 'body']

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

In [24]:
# Save API data as a CSV file

api_csv_file = "api_posts.csv"

api_df.to_csv(api_csv_file, index=False)

print("API data saved successfully!")
print("File name:", api_csv_file)
print("Records saved:", len(api_df))


# In this block, I am saving the data retrieved from the API into a CSV file.

# The to_csv() method converts the Pandas DataFrame into a CSV file.
# I use index=False because I don't want Pandas to add its row index as an extra column.

# Finally, I print the file name and the number of records saved to verify the operation.

# This demonstrates a basic data ingestion workflow: retrieve data from an external API,
# convert it into a DataFrame, and store it in a reusable file format.

API data saved successfully!
File name: api_posts.csv
Records saved: 100

In [25]:
# Read the API CSV and validate it


api_df_check = pd.read_csv(api_csv_file)

print("Original API DataFrame shape:", api_df.shape)
print("Reloaded CSV DataFrame shape:", api_df_check.shape)

print("\nFirst 5 rows from the reloaded CSV:")
display(api_df_check.head())

# In this block, I am validating the CSV file that I saved in the previous step.

# I use `pd.read_csv()` to load the saved file into a new DataFrame called `api_df_check`.

# Then I compare the shapes of the original DataFrame and the reloaded DataFrame. The shape tells me the number of rows and columns.

# Finally, I display the first five rows to verify that the data is readable.

# If both DataFrames have the same shape and the records look correct,
#  it provides a basic validation that the data was saved and loaded successfully.

Original API DataFrame shape: (100, 4)
Reloaded CSV DataFrame shape: (100, 4)

First 5 rows from the reloaded CSV:

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

In [26]:

print("Are all values identical?")
print(api_df.equals(api_df_check))

Are all values identical?
True

In [27]:
# Check the available data files


import os

print("Files available in the current Colab session:")
print(os.listdir())

# In this block, I am inspecting the files available in the current Colab environment.

# The `os` module provides functions for interacting with the operating system.

# The `listdir()` function lists the files and folders in the current working directory.

# This helps me understand which datasets and output files are available before downloading or processing additional data.

# In a real project, checking the available files is a simple way to avoid accidentally overwriting files or loading the wrong dataset.

Files available in the current Colab session:
['.config', 'WA_Fn-UseC_-Telco-Customer-Churn.csv', 'customer_churn.xlsx', 'customer_churn.parquet', 'api_posts.csv', 'customer_churn.json', 'sample_data']

In [28]:

import requests

dataset_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

download_response = requests.get(dataset_url, timeout=30)

print("HTTP status code:", download_response.status_code)
print("Downloaded content length:", len(download_response.content), "bytes")

# In this block, I am downloading a dataset directly from a public URL.

# Unlike the previous API example, where the server returned structured JSON records,
# this URL provides a dataset file containing comma-separated values.

# I use the requests library to send an HTTP GET request.
# The status code tells me whether the request succeeded, and the content length tells me how many bytes were received.

# I am using this dataset only to demonstrate external file acquisition.
# Since it contains flower measurements rather than customer information, I will keep it separate from the churn project.

HTTP status code: 200
Downloaded content length: 4551 bytes

In [29]:
# Load the downloaded dataset


from io import BytesIO

iris_columns = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width",
    "species"
]

iris_df = pd.read_csv(
    BytesIO(download_response.content),
    header=None,
    names=iris_columns
)

print("Dataset shape:", iris_df.shape)
print("\nFirst 5 rows:")
display(iris_df.head())


# In this block, I am converting the downloaded dataset into a Pandas DataFrame.

# The response content contains the downloaded file as bytes. `BytesIO` allows Pandas to read those bytes as if they were a file.

# The dataset does not include column headers, so I provide five column names using the `names` parameter and set `header=None`.

# Finally, I print the dataset shape and display the first five rows to understand its structure.

# This demonstrates a common data acquisition workflow: download a file, parse it into a DataFrame,
# and inspect the resulting data before further processing.

Dataset shape: (150, 5)

First 5 rows:

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [30]:
# Now going for model understanding, performance metrics analysis of customer churn

# Inspect the target and feature columns


print("Dataset shape:", df.shape)

print("\nTarget column:")
print("Churn")

print("\nTarget values:")
print(df["Churn"].value_counts())

print("\nData types:")
print(df.dtypes)


# Before training a machine-learning model, I need to understand the structure of my dataset.

# The shape tells me how many customer records and columns are available.

# My target variable is Churn, because I want to predict whether a customer will leave the service.

# The value counts show the categories the model needs to predict, such as Yes and No.

# Finally, the data types help me identify numerical and categorical columns.
# This matters because most machine-learning algorithms require categorical data to be converted into a numerical representation
# before training.

# This inspection helps me plan the data preparation process correctly.

Dataset shape: (7043, 21)

Target column:
Churn

Target values:
Churn
No     5174
Yes    1869
Name: count, dtype: int64

Data types:
customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [31]:
# Clean TotalCharges


total_charges_numeric = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)

print("Original TotalCharges data type:", df["TotalCharges"].dtype)
print("Missing or non-numeric values:", total_charges_numeric.isna().sum())

# In this block, I am investigating the TotalCharges column before cleaning it.

# The `pd.to_numeric()` function attempts to convert the column into numerical values.

# I use `errors="coerce"` so that any value that cannot be converted becomes a missing value,
# represented by NaN, instead of causing the code to fail.

# Finally, I print the original data type and count the missing or non-numeric values.
# This helps me understand the scale of the data-quality issue before deciding how to handle it.

# Notice that I have not modified the original dataset yet. I am first checking the problem
# so that the next cleaning step is based on evidence.

Original TotalCharges data type: object
Missing or non-numeric values: 11

In [33]:
# Inspect the affected records


invalid_total_charges = df.loc[
    total_charges_numeric.isna(),
    ["customerID", "tenure", "MonthlyCharges", "TotalCharges", "Churn"]
]

display(invalid_total_charges)

# In this block, I am inspecting the records where TotalCharges could not be converted into a number.

# The `isna()` method identifies the invalid values in the converted column.

# The `loc` accessor selects only those records and displays five relevant columns:
# customer ID, tenure, monthly charges, total charges, and churn status.

# By comparing tenure and monthly charges with TotalCharges,
# I can investigate whether these are genuinely missing values or whether there is a reasonable explanation for them.

# This helps me make a data-cleaning decision based on evidence rather than assumptions.

      customerID  tenure  MonthlyCharges TotalCharges Churn
488   4472-LVYGI       0           52.55                 No
753   3115-CZMZD       0           20.25                 No
936   5709-LVOEQ       0           80.85                 No
1082  4367-NUYAO       0           25.75                 No
1340  1371-DWPAZ       0           56.05                 No
3331  7644-OMVMY       0           19.85                 No
3826  3213-VVOLG       0           25.35                 No
4380  2520-SGTTA       0           20.00                 No
5218  2923-ARZLG       0           19.70                 No
6670  4075-WKNIU       0           73.35                 No
6754  2775-SEFEE       0           61.90                 No

In [34]:
# Clean TotalCharges


df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
).fillna(0)

print("TotalCharges data type:", df["TotalCharges"].dtype)
print("Missing TotalCharges values:", df["TotalCharges"].isna().sum())
print("Records with zero tenure:", (df["tenure"] == 0).sum())

# In this block, I am cleaning the TotalCharges column.

# First, I convert the column into a numerical data type using `pd.to_numeric()`.

# The `errors="coerce"` parameter converts invalid values into missing values.

# Next, `fillna(0)` replaces missing values with zero. Based on our inspection,
# all 11 affected customers have zero tenure, so zero total charges is a reasonable interpretation for this dataset.

# Finally, I verify the data type, check whether any missing values remain, and count customers with zero tenure.

# This step prepares TotalCharges for machine learning while making the cleaning decision transparent and verifiable.

TotalCharges data type: float64
Missing TotalCharges values: 0
Records with zero tenure: 11

In [35]:
#  Prepare features and target


X = df.drop(columns=["Churn", "customerID"])
y = df["Churn"].map({"No": 0, "Yes": 1})

print("Feature matrix shape:", X.shape)
print("Target shape:", y.shape)
print("\nTarget values:")
print(y.value_counts())

# In this block, I am separating the input features from the target variable.

# The variable X contains the customer information that the model will use to make predictions. I remove Churn because it is the answer we want the model to learn to predict. I also remove customerID because it is an identifier rather than a meaningful behavioral feature.

# The variable y contains the actual churn outcome.
#  I convert No to zero and Yes to one because machine-learning algorithms work conveniently with numerical target labels.

# Finally, I print the shapes of X and y and check the target counts to confirm that the features and labels are aligned.

# This separation is the foundation of supervised machine learning.

Feature matrix shape: (7043, 19)
Target shape: (7043,)

Target values:
Churn
0    5174
1    1869
Name: count, dtype: int64

In [36]:
# Identify numerical and categorical columns


numerical_columns = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_columns = X.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

print("Numerical columns:", len(numerical_columns))
print(numerical_columns)

print("\nCategorical columns:", len(categorical_columns))
print(categorical_columns)

# Before splitting the data, I am identifying which features are numerical and which are categorical.

# I use `select_dtypes()` to select columns based on their data types.

# Numerical columns contain values such as tenure and monthly charges.
# Categorical columns contain labels such as contract type, payment method, and internet service.

# This distinction matters because different types of features require different preprocessing methods.

# For this project, we will keep numerical features as numerical values and
# apply one-hot encoding to categorical features. We will then build a preprocessing pipeline and
# split the data before fitting any transformations, so information from the test set cannot leak into training.

Numerical columns: 4
['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

Categorical columns: 15
['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

In [37]:
# Split the data before preprocessing
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)

print("\nTraining churn rate:", round(y_train.mean() * 100, 2), "%")
print("Testing churn rate:", round(y_test.mean() * 100, 2), "%")

Training features: (5634, 19)
Testing features: (1409, 19)

Training churn rate: 26.54 %
Testing churn rate: 26.54 %

In [38]:
# Build the preprocessing pipeline


from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

preprocessor = ColumnTransformer(
    transformers=[
        ("num", "passthrough", numerical_columns),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_columns)
    ]
)

print("Preprocessing pipeline created successfully.")
print("Numerical columns:", len(numerical_columns))
print("Categorical columns:", len(categorical_columns))

# In this block, I am building a preprocessing pipeline for my customer churn model.

# I use ColumnTransformer to apply different preprocessing rules to different groups of columns.

# For numerical columns, I use passthrough, which keeps their values unchanged.

# For categorical columns, I use OneHotEncoder to convert categories into numerical indicator columns.
# I set handle_unknown to ignore so the pipeline can process categories that were not present when the encoder was fitted.

# I also import Pipeline because we will use it to connect preprocessing with the machine-learning model in a later step.

# At this stage, I am only defining the preprocessing instructions. I am not fitting the encoder or training the model yet.
#  We will fit everything using the training data only.

Preprocessing pipeline created successfully.
Numerical columns: 4
Categorical columns: 15

In [39]:
# Fit and transform the training data


X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print("Training data before preprocessing:", X_train.shape)
print("Training data after preprocessing:", X_train_processed.shape)

print("\nTesting data before preprocessing:", X_test.shape)
print("Testing data after preprocessing:", X_test_processed.shape)


# In this block, I am applying the preprocessing instructions to the training and testing datasets.

# For the training data, I use fit_transform.
# The fit operation learns the categories present in the training set, and the transform operation converts the features into the required numerical representation.

# For the testing data, I use only transform.
# This reuses the categories learned from the training data instead of learning anything new from the test set.

# I then compare the shapes before and after preprocessing.
# The number of rows should remain unchanged,
# but the number of columns will usually increase because one-hot encoding creates additional columns for categorical values.

# This step prepares the features for machine learning while keeping the test data separate from the fitting process.

Training data before preprocessing: (5634, 19)
Training data after preprocessing: (5634, 45)

Testing data before preprocessing: (1409, 19)
Testing data after preprocessing: (1409, 45)

In [40]:
# Check feature cardinality


feature_summary = pd.DataFrame({
    "Data_Type": X.dtypes.astype(str),
    "Unique_Values": X.nunique(),
    "Missing_Values": X.isna().sum()
})

display(
    feature_summary.sort_values(
        "Unique_Values",
        ascending=False
    )
)

# Before training the model, I am inspecting the remaining features to understand their data types, number of distinct values,
#  and missing values.

# The `nunique()` method counts the distinct values in each column.
# This helps identify features with many unique values, which may need special attention, and features with very few values, such as binary categories.

# The missing-value count helps us identify any remaining data-quality issues.

# I will use this summary to check whether any features should be excluded or require additional preprocessing.
# I won't automatically remove a feature just because it has few unique values or seems less important.
#  Feature selection should be justified by the data and evaluated against model performance.

                 Data_Type  Unique_Values  Missing_Values
TotalCharges       float64           6531               0
MonthlyCharges     float64           1585               0
tenure               int64             73               0
PaymentMethod       object              4               0
Contract            object              3               0
DeviceProtection    object              3               0
StreamingMovies     object              3               0
OnlineBackup        object              3               0
MultipleLines       object              3               0
OnlineSecurity      object              3               0
InternetService     object              3               0
StreamingTV         object              3               0
TechSupport         object              3               0
gender              object              2               0
SeniorCitizen        int64              2               0
Partner             object              2               0
PhoneService        object              2               0
Dependents          object              2               0
PaperlessBilling    object              2               0

In [41]:
# Train the baseline Logistic Regression model


from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

model.fit(X_train_processed, y_train)

print("Baseline Logistic Regression trained.")
print("Training samples:", X_train_processed.shape[0])
print("Features used:", X_train_processed.shape[1])

# I have inspected the feature summary and found no remaining missing values in the input features.
#  I also confirmed that the remaining columns contain meaningful customer information rather than an obvious identifier.

# I will now train a baseline Logistic Regression model using all 45 processed features.

# A baseline gives me a reference point.
# Later, I can examine the model coefficients and evaluate whether removing selected features improves performance.

# The fit method learns the relationship between the training features and the churn labels.
# Finally, I print the number of training samples and processed features to verify the training setup.

Baseline Logistic Regression trained.
Training samples: 5634
Features used: 45

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [42]:
# Update the preprocessing pipeline


from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_columns),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_columns)
    ]
)

print("Preprocessing updated with numerical feature scaling.")

# The model training produced a convergence warning, so I am improving the preprocessing before continuing.

# Previously, I passed numerical features through unchanged.
# Now, I am using StandardScaler to standardize them.
# This transforms numerical values to a common scale based on the training data's mean and standard deviation when the pipeline is fitted.

# Scaling often helps Logistic Regression's optimization algorithm converge more reliably,
# especially when features have very different magnitudes.

# I am keeping one-hot encoding for categorical features and
# setting handle_unknown to ignore so unseen categories can be handled safely.

# This block only defines the updated preprocessing instructions.
# In the next step, I will fit the updated preprocessing on the training data and transform both datasets consistently.

Preprocessing updated with numerical feature scaling.

In [43]:
# Reprocess training and testing data


X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print("Training data shape:", X_train_processed.shape)
print("Testing data shape:", X_test_processed.shape)
print("Preprocessing completed.")


# In this block, I am applying the updated preprocessing pipeline.

# I use fit_transform on the training data.
# This learns the scaling parameters from the training numerical features and learns the categorical values for one-hot encoding.

# I then use transform on the testing data, applying the same learned scaling parameters and category mapping without fitting again.

# Finally, I print both shapes to verify that preprocessing completed successfully.
# The number of rows should remain unchanged, and both datasets should have the same number of processed features.

# This ensures that the model will train and be evaluated using consistently transformed data,
# without learning preprocessing information from the test set.

Training data shape: (5634, 45)
Testing data shape: (1409, 45)
Preprocessing completed.

In [44]:
# Retrain Logistic Regression


from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=2000,
    random_state=42
)

model.fit(X_train_processed, y_train)

print("Logistic Regression retrained successfully.")
print("Iterations used:", model.n_iter_[0])

# In this block, I am retraining Logistic Regression using the updated,
# standardized numerical features and one-hot encoded categorical features.

# I set the maximum number of iterations to 2,000 to give the optimization algorithm more opportunity to converge.

# The fit method learns the model coefficients from the training data and its churn labels.

# Finally, I print the number of iterations the model actually used.
# This helps me inspect how the optimization process progressed.
# If a convergence warning still appears, we will investigate further rather than assume that increasing the iteration limit fixed it.

Logistic Regression retrained successfully.
Iterations used: 42

In [45]:
# Make predictions on test data


y_pred = model.predict(X_test_processed)

print("Number of test customers:", len(y_test))
print("Number of predictions:", len(y_pred))

print("\nFirst 10 actual churn labels:")
print(y_test.iloc[:10].tolist())

print("\nFirst 10 predicted churn labels:")
print(y_pred[:10].tolist())

# In this block, I am using the trained model to predict churn for the testing dataset.

# The predict method takes the processed test features and returns a predicted class for each customer.
# Zero means the model predicts that the customer will stay, and one means it predicts that the customer will churn.

# I print the number of actual test labels and predictions to verify that every test customer has a corresponding prediction.

# Then I compare the first ten actual labels with the first ten predicted labels.
# This gives me an initial look at the predictions, although we need formal performance metrics to evaluate the model reliably.

Number of test customers: 1409
Number of predictions: 1409

First 10 actual churn labels:
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1]

First 10 predicted churn labels:
[0, 1, 0, 0, 0, 1, 0, 0, 0, 0]

The model generated 1,409 predictions, matching the number of customers in the test set.

When I compare the first ten actual labels with the predicted labels, I see that eight predictions are correct and two are incorrect.

The model incorrectly predicts churn for two customers who actually stayed, and it predicts that one customer will stay when that customer actually churned.

This is only a small sample, so I cannot use it to judge the model's overall performance. I need metrics such as accuracy, precision, recall, and F1-score to understand how well it performs across the complete test dataset.

In [46]:
# Evaluate accuracy


from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Test accuracy:", round(accuracy * 100, 2), "%")

# In this block, I am calculating the model's accuracy on the test dataset.

# Accuracy is the number of correct predictions divided by the total number of predictions.

# I use `accuracy_score()` to compare the actual churn labels with the model's predicted labels,
# then multiply the result by 100 to express it as a percentage.

# Accuracy gives me a useful first measure of performance.
#  However, our dataset is imbalanced because only about 26.54 percent of customers churned.
#  Therefore, I will also examine precision, recall, and F1-score to understand
#  whether the model identifies customers who are actually at risk of leaving.

Test accuracy: 80.55 %

In [48]:
# Calculate precision, recall, and F1-score


from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", round(precision * 100, 2), "%")
print("Recall:", round(recall * 100, 2), "%")
print("F1-score:", round(f1 * 100, 2), "%")

# In this block, I am calculating three important classification metrics.

# Precision measures, among the customers the model predicted would churn, how many actually churned.

# Recall measures, among all customers who actually churned, how many the model successfully identified.

# F1-score combines precision and recall into a single metric using their harmonic mean. It is useful when I want to balance the two.

# I am calculating these metrics using the test labels and predictions, with churn represented by one as the positive class.

# These metrics will help me understand whether the model's accuracy translates into useful churn detection for the business.

Precision: 65.72 %
Recall: 55.88 %
F1-score: 60.4 %

In [49]:
# Build the confusion matrix


from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

# In this block, I am generating a confusion matrix to examine the model's predictions in detail.

# The confusion matrix compares actual labels with predicted labels.
# For a binary classification problem, it contains four counts: true negatives, false positives, false negatives, and true positives.

# The first row represents customers who actually stayed, and the second row represents customers who actually churned.
# The columns represent the predicted classes, zero and one.

# This matrix will show how many customers were classified correctly and, more importantly,
# how many churners the model missed. That will help us understand the recall result and decide what to improve next.

Confusion Matrix:
[[926 109]
 [165 209]]

The confusion matrix gives me four important numbers.

The model correctly predicted that 926 customers would stay. These are true negatives.

It incorrectly flagged 109 customers as churners even though they stayed. These are false positives.

It missed 165 customers who actually churned. These are false negatives, and they represent a major business opportunity because the company could potentially have intervened.

Finally, the model correctly identified 209 customers who churned. These are true positives.

There were 374 actual churners in the test set, and the model identified 209 of them. This explains why recall is approximately 55.88 percent.

Our next objective is to understand which features influence the model's predictions and explore ways to improve churn detection.

In [50]:
# Inspect the model's most influential features


feature_names = preprocessor.get_feature_names_out()

coefficient_df = pd.DataFrame({
    "Feature": feature_names,
    "Coefficient": model.coef_[0]
})

coefficient_df["Abs_Coefficient"] = (
    coefficient_df["Coefficient"].abs()
)

display(
    coefficient_df.sort_values(
        "Abs_Coefficient",
        ascending=False
    ).head(15)
)


# In this block, I am inspecting the coefficients learned by Logistic Regression.

# Each coefficient represents how a feature is associated with the model's predicted log-odds of churn, holding the other features constant.
#  A positive coefficient is associated with higher predicted churn, while a negative coefficient is associated with lower predicted churn.

# I retrieve the transformed feature names from the preprocessing pipeline so that the coefficients can be linked to the correct numerical
# or one-hot encoded feature.

# I then calculate the absolute value of each coefficient and display the 15 largest by magnitude.
# This gives me a first look at which features have the strongest coefficient values.

# However, coefficient magnitude alone does not prove that a feature is the most important predictor,
# and it does not establish causation. We should interpret the results carefully, especially when features are correlated.

                                      Feature  Coefficient  Abs_Coefficient
1                                 num__tenure    -1.257539         1.257539
38                     cat__Contract_Two year    -0.776594         0.776594
15                   cat__InternetService_DSL    -0.648646         0.648646
16           cat__InternetService_Fiber optic     0.634195         0.634195
2                         num__MonthlyCharges    -0.591863         0.591863
36               cat__Contract_Month-to-month     0.582883         0.582883
3                           num__TotalCharges     0.536253         0.536253
39                   cat__PaperlessBilling_No    -0.343227         0.343227
25  cat__DeviceProtection_No internet service    -0.300104         0.300104
17                    cat__InternetService_No    -0.300104         0.300104
19    cat__OnlineSecurity_No internet service    -0.300104         0.300104
28       cat__TechSupport_No internet service    -0.300104         0.300104
31       cat__StreamingTV_No internet service    -0.300104         0.300104
22      cat__OnlineBackup_No internet service    -0.300104         0.300104
34   cat__StreamingMovies_No internet service    -0.300104         0.300104

In [51]:
# Get churn probabilities


y_prob = model.predict_proba(X_test_processed)[:, 1]

print("First 10 churn probabilities:")
print(y_prob[:10].round(3))

print("\nMinimum churn probability:", round(y_prob.min(), 3))
print("Maximum churn probability:", round(y_prob.max(), 3))

# In this block, I am retrieving the model's predicted probability of churn for every customer in the test set.

# The `predict_proba()` method returns a probability for each class.
#  Column zero represents the probability that a customer will stay, and column one represents the probability that the customer will churn.

# By selecting column one, I store the churn probabilities in `y_prob`.

# I then display the first ten probabilities and the minimum and maximum values.

# These probabilities give us more flexibility than class predictions alone.
#  Instead of being restricted to the default threshold of 0.5, we can test different thresholds and observe how precision and recall change.

First 10 churn probabilities:
[0.046 0.684 0.059 0.402 0.021 0.603 0.448 0.13  0.003 0.395]

Minimum churn probability: 0.002
Maximum churn probability: 0.854

The model has generated a churn probability for each customer in the test set.

For example, the first customer's estimated churn probability is 4.6 percent, while the second customer's probability is 68.4 percent.

The model's probabilities range from 0.2 percent to 85.4 percent in this test set.

At the default threshold of 0.5, probabilities at or above 50 percent are classified as churn, and probabilities below 50 percent are classified as no churn.

The important point is that the model produces probabilities first, and the classification threshold converts those probabilities into final predictions. By adjusting that threshold, we can change the balance between identifying churners and avoiding false alarms.

In [52]:
# Compare different thresholds


from sklearn.metrics import precision_score, recall_score, f1_score

for threshold in [0.3, 0.4, 0.5]:
    y_threshold_pred = (y_prob >= threshold).astype(int)

    print(f"\nThreshold: {threshold}")
    print("Precision:", round(precision_score(y_test, y_threshold_pred) * 100, 2), "%")
    print("Recall:", round(recall_score(y_test, y_threshold_pred) * 100, 2), "%")
    print("F1-score:", round(f1_score(y_test, y_threshold_pred) * 100, 2), "%")

Threshold: 0.3
Precision: 51.93 %
Recall: 75.4 %
F1-score: 61.5 %

Threshold: 0.4
Precision: 56.82 %
Recall: 66.84 %
F1-score: 61.43 %

Threshold: 0.5
Precision: 65.72 %
Recall: 55.88 %
F1-score: 60.4 %

The threshold comparison shows that changing the classification threshold changes the balance between precision and recall.

At the default threshold of 0.5, precision is 65.72 percent and recall is 55.88 percent.

When I lower the threshold to 0.3, recall increases to 75.4 percent. This means the model identifies a larger proportion of actual churners. However, precision falls to 51.93 percent, so more customers flagged as churn risks may actually stay.

The threshold of 0.4 provides an intermediate result, with 56.82 percent precision and 66.84 percent recall.

If the business prioritizes identifying more customers before they leave, I would investigate the lower threshold. Before making a final decision, I would also consider retention costs and validate the chosen threshold on separate validation data.

In [53]:
# Count the predicted churners


for threshold in [0.3, 0.4, 0.5]:
    y_threshold_pred = (y_prob >= threshold).astype(int)

    predicted_churners = int(y_threshold_pred.sum())

    print(
        f"Threshold {threshold}: "
        f"{predicted_churners} customers flagged for churn risk"
    )

#     In this block, I am counting how many test customers would be flagged as potential churners at each threshold.

# For every threshold, I convert the churn probabilities into binary predictions.
# Then I sum the predictions.
# Because churn is represented by one and non-churn by zero, the sum gives the number of customers predicted to churn.

# This translates model behavior into a practical business question: how many customers would the retention team need to review or contact?

# A lower threshold will generally flag more customers.
# The company needs to balance that workload against the benefit of identifying more customers who may leave.

Threshold 0.3: 543 customers flagged for churn risk
Threshold 0.4: 440 customers flagged for churn risk
Threshold 0.5: 318 customers flagged for churn risk

In [54]:
# Compare confusion matrices


from sklearn.metrics import confusion_matrix

for threshold in [0.5, 0.3]:
    y_threshold_pred = (y_prob >= threshold).astype(int)
    cm = confusion_matrix(y_test, y_threshold_pred)

    print(f"\nThreshold: {threshold}")
    print("Confusion matrix:")
    print(cm)

    tn, fp, fn, tp = cm.ravel()
    print("True Negatives:", tn)
    print("False Positives:", fp)
    print("False Negatives:", fn)
    print("True Positives:", tp)

# In this block, I am comparing the confusion matrices at thresholds 0.5 and 0.3.

# For each threshold, I convert the predicted probabilities into binary predictions and calculate the confusion matrix.

# The matrix gives me four counts: true negatives, false positives, false negatives, and true positives.

# I use `ravel()` to unpack the four values in that order.

# By comparing the results, I can see whether lowering the threshold helps identify more actual churners,
#  how many additional false alarms it creates, and how many churners are still missed.

# This is useful because precision and recall describe performance as percentages,
# while the confusion matrix translates that performance into actual customer counts.

Threshold: 0.5
Confusion matrix:
[[926 109]
 [165 209]]
True Negatives: 926
False Positives: 109
False Negatives: 165
True Positives: 209

Threshold: 0.3
Confusion matrix:
[[774 261]
 [ 92 282]]
True Negatives: 774
False Positives: 261
False Negatives: 92
True Positives: 282

In [55]:
# Calculate ROC-AUC


from sklearn.metrics import roc_auc_score

roc_auc = roc_auc_score(y_test, y_prob)

print("ROC-AUC score:", round(roc_auc, 4))

# In this block, I am calculating the ROC-AUC score for the churn prediction model.

# Unlike accuracy, precision, and recall at a specific threshold,
# ROC-AUC evaluates how well the model ranks customers who actually churned above customers
# who stayed across different classification thresholds.

# A score closer to one indicates stronger separation between the two groups,
#  while a score around 0.5 indicates performance similar to random ranking.

# I use the actual test labels and the predicted churn probabilities, rather than the binary predictions,
# because ROC-AUC evaluates ranking across thresholds.

# This gives me another perspective on model performance that is not tied to choosing a single threshold.

ROC-AUC score: 0.8421

My Logistic Regression model achieved a ROC-AUC score of 0.8421 on the test dataset.

ROC-AUC measures the model's ability to distinguish between customers who churn and customers who stay across different classification thresholds.

A score of approximately 0.84 indicates that the model has useful ranking ability. For a randomly selected churner and non-churner, it will rank the churner higher approximately 84 percent of the time, subject to the handling of tied scores.

This is different from accuracy. Accuracy measures the proportion of correct predictions at a particular threshold, while ROC-AUC evaluates ranking performance across thresholds.

The result suggests that the model can distinguish between churn risks reasonably well, although we still need to consider recall, precision, and business costs when choosing how to use it.

In [56]:
# Create three separate datasets

# - 60% training: fit preprocessing and train the model.
# - 20% validation: choose the classification threshold.
# - 20% testing: evaluate the final model and chosen threshold.



from sklearn.model_selection import train_test_split

X_train_new, X_temp, y_train_new, y_temp = train_test_split(
    X,
    y,
    test_size=0.40,
    random_state=123,
    stratify=y
)

X_val, X_test_new, y_val, y_test_new = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=123,
    stratify=y_temp
)

print("Training set:", X_train_new.shape)
print("Validation set:", X_val.shape)
print("Testing set:", X_test_new.shape)

print("\nTraining churn rate:", round(y_train_new.mean() * 100, 2), "%")
print("Validation churn rate:", round(y_val.mean() * 100, 2), "%")
print("Testing churn rate:", round(y_test_new.mean() * 100, 2), "%")


# In this block, I am creating three separate datasets for a more reliable model evaluation.

# The training set will be used to learn the preprocessing transformations and train the Logistic Regression model.

# The validation set will help me select a suitable classification threshold based on metrics such as precision, recall, and F1-score.

# The testing set will be reserved for the final evaluation after the model and threshold have been selected.

# I use stratified splitting to preserve approximately the same proportion of churn and non-churn customers in each dataset.
# I also use fixed random states so the splits can be reproduced.

# Separating these responsibilities helps prevent us from choosing a threshold based on the same data used to report final performance.

Training set: (4225, 19)
Validation set: (1409, 19)
Testing set: (1409, 19)

Training churn rate: 26.53 %
Validation churn rate: 26.54 %
Testing churn rate: 26.54 %

In [57]:
# Fit preprocessing on training data only


preprocessor_final = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_columns),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_columns)
    ]
)

X_train_final = preprocessor_final.fit_transform(X_train_new)
X_val_final = preprocessor_final.transform(X_val)
X_test_final = preprocessor_final.transform(X_test_new)

print("Training data after preprocessing:", X_train_final.shape)
print("Validation data after preprocessing:", X_val_final.shape)
print("Testing data after preprocessing:", X_test_final.shape)

# In this block, I am creating a fresh preprocessing pipeline for the new training, validation, and testing datasets.

# I standardize numerical features and one-hot encode categorical features.
# I fit the preprocessor only on the training data, allowing it to learn scaling parameters and
# categorical values without seeing the validation or test data.

# I then transform the validation and test datasets using the already fitted preprocessor.

# Finally, I print the shapes to confirm that all three datasets have compatible feature structures.
# This ensures the validation and test data receive exactly the same preprocessing rules as the training data.

Training data after preprocessing: (4225, 45)
Validation data after preprocessing: (1409, 45)
Testing data after preprocessing: (1409, 45)

In [58]:
# Train the final Logistic Regression model


model_final = LogisticRegression(
    max_iter=2000,
    random_state=42
)

model_final.fit(X_train_final, y_train_new)

print("Final Logistic Regression model trained.")
print("Iterations used:", model_final.n_iter_[0])

Final Logistic Regression model trained.
Iterations used: 24

In [59]:
# Compare thresholds on validation data


from sklearn.metrics import precision_score, recall_score, f1_score

y_val_prob = model_final.predict_proba(X_val_final)[:, 1]

for threshold in [0.3, 0.4, 0.5]:
    y_val_pred = (y_val_prob >= threshold).astype(int)

    print(f"\nThreshold: {threshold}")
    print("Precision:", round(precision_score(y_val, y_val_pred) * 100, 2), "%")
    print("Recall:", round(recall_score(y_val, y_val_pred) * 100, 2), "%")
    print("F1-score:", round(f1_score(y_val, y_val_pred) * 100, 2), "%")

#     In this block, I am evaluating different classification thresholds using the validation dataset.

# First, I obtain the model's predicted probability of churn for each validation customer.

# Then, I test thresholds of 0.3, 0.4, and 0.5. For each threshold, I convert probabilities into binary predictions and calculate precision,
#  recall, and F1-score.

# I use the validation data for this comparison because it is intended for selecting model settings such as the classification threshold.

# After reviewing these results, I will choose a threshold based on the business objective.
# Only after that decision will I evaluate the selected threshold on the separate test dataset.

Threshold: 0.3
Precision: 53.89 %
Recall: 75.94 %
F1-score: 63.04 %

Threshold: 0.4
Precision: 58.8 %
Recall: 65.24 %
F1-score: 61.85 %

Threshold: 0.5
Precision: 64.82 %
Recall: 53.21 %
F1-score: 58.44 %

The validation results show that threshold 0.3 achieves 75.94 percent recall and an F1-score of 63.04 percent.

Threshold 0.4 gives higher precision but lower recall, while threshold 0.5 has the highest precision of the three but identifies fewer actual churners.

Because our current objective is to identify more customers who may leave, I will select threshold 0.3 for the final evaluation.

I made this decision using the validation dataset, not the test dataset. The test set remains reserved for evaluating how the chosen model and threshold perform on unseen data.

In [60]:

selected_threshold = 0.3

print("Selected threshold:", selected_threshold)
print("Selection basis: validation recall and F1-score")

Selected threshold: 0.3
Selection basis: validation recall and F1-score

In this block, I am recording the classification threshold selected from the validation results.

I assign 0.3 to a variable called selected_threshold so that I can reuse the decision consistently during final evaluation.

I also print the threshold and the reason for selecting it. This makes the model configuration explicit and easier to reproduce.

The next step is to apply this selected threshold to the untouched test probabilities and evaluate the final model performance.

In [61]:
# Final test evaluation


from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

y_test_prob = model_final.predict_proba(X_test_final)[:, 1]
y_test_final_pred = (y_test_prob >= selected_threshold).astype(int)

print("Selected threshold:", selected_threshold)
print("Accuracy:", round(accuracy_score(y_test_new, y_test_final_pred) * 100, 2), "%")
print("Precision:", round(precision_score(y_test_new, y_test_final_pred) * 100, 2), "%")
print("Recall:", round(recall_score(y_test_new, y_test_final_pred) * 100, 2), "%")
print("F1-score:", round(f1_score(y_test_new, y_test_final_pred) * 100, 2), "%")
print("ROC-AUC:", round(roc_auc_score(y_test_new, y_test_prob), 4))

print("\nConfusion matrix:")
print(confusion_matrix(y_test_new, y_test_final_pred))

# In this block, I am conducting the final evaluation of my churn prediction model.

# First, I generate churn probabilities for the untouched test dataset.
# I apply the threshold of 0.3 that I selected using the validation dataset, converting probabilities into binary predictions.

# I then calculate accuracy, precision, recall, F1-score, and ROC-AUC.
# The first four metrics evaluate classification performance at the selected threshold,
# while ROC-AUC measures the model's ability to rank churners above non-churners across thresholds.

# Finally, I print the confusion matrix to see the actual counts of correct predictions and errors.

# Because I reserved the test set for this final evaluation,
# these results provide a more reliable estimate of how the selected model configuration may perform on unseen customers.

Selected threshold: 0.3
Accuracy: 76.44 %
Precision: 54.04 %
Recall: 75.13 %
F1-score: 62.86 %
ROC-AUC: 0.8465

Confusion matrix:
[[796 239]
 [ 93 281]]

“After selecting the classification threshold using the validation dataset, I evaluated my final Logistic Regression model on a separate test dataset.

I selected a threshold of 0.3 because the business goal was to identify more customers who might churn.

The model achieved 76.44% accuracy, 54.04% precision, 75.13% recall, an F1-score of 62.86%, and a ROC-AUC of 0.8465.

The confusion matrix shows that the model correctly identified 281 churners and missed 93. It also flagged 239 customers who ultimately did not churn.

This demonstrates the trade-off between identifying more potential churners and generating more false positives.

The next step would be to estimate the financial cost of missed churners versus retention campaign costs before deciding whether this threshold is commercially optimal.”

In [62]:
# Verify deployment objects

required_objects = [
    "preprocessor_final",
    "model_final",
    "selected_threshold",
    "numerical_columns",
    "categorical_columns"
]

for object_name in required_objects:
    print(f"{object_name}: {object_name in globals()}")


# “I am checking whether all the objects required for deployment exist in my current notebook session.
# These include the fitted preprocessing pipeline, trained Logistic Regression model,
# selected classification threshold, and feature-column lists.
# I need these objects to package the model consistently before building the application.”

preprocessor_final: True
model_final: True
selected_threshold: True
numerical_columns: True
categorical_columns: True

In [63]:
# Package the model

import joblib

deployment_artifact = {
    "preprocessor": preprocessor_final,
    "model": model_final,
    "threshold": selected_threshold,
    "numerical_columns": numerical_columns,
    "categorical_columns": categorical_columns
}

joblib.dump(deployment_artifact, "customer_churn_model.joblib")

print("Model package saved successfully.")
print("File: customer_churn_model.joblib")
print("Selected threshold:", deployment_artifact["threshold"])

# “I am packaging the complete machine learning solution into one file.
# The package contains the fitted preprocessing pipeline, trained Logistic Regression model, selected threshold of 0.3,
#  and the numerical and categorical feature lists.
# Saving these together helps ensure that the deployed application processes customer data consistently with the training workflow.”

Model package saved successfully.
File: customer_churn_model.joblib
Selected threshold: 0.3

In [64]:
# Reload and verify the model package

import joblib

loaded_artifact = joblib.load("customer_churn_model.joblib")

print("Model package loaded successfully.")
print("Model type:", type(loaded_artifact["model"]).__name__)
print("Preprocessor type:", type(loaded_artifact["preprocessor"]).__name__)
print("Selected threshold:", loaded_artifact["threshold"])
print("Numerical features:", len(loaded_artifact["numerical_columns"]))
print("Categorical features:", len(loaded_artifact["categorical_columns"]))

Model package loaded successfully.
Model type: LogisticRegression
Preprocessor type: ColumnTransformer
Selected threshold: 0.3
Numerical features: 4
Categorical features: 15

In [65]:
from google.colab import files

files.download("customer_churn_model.joblib")

In [66]:
%%writefile app.py
import streamlit as st
import pandas as pd
import joblib

artifact = joblib.load("customer_churn_model.joblib")

preprocessor = artifact["preprocessor"]
model = artifact["model"]
threshold = artifact["threshold"]
numerical_columns = artifact["numerical_columns"]
categorical_columns = artifact["categorical_columns"]

st.set_page_config(
    page_title="Customer Churn Prediction",
    page_icon="📊",
    layout="centered"
)

st.title("Customer Churn Prediction")
st.write("Enter customer details to estimate their churn risk.")

st.success("Model loaded successfully.")
st.caption(f"Prediction threshold: {threshold}")

Writing app.py

In [67]:
# Create customer input fields

%%writefile -a app.py

st.header("Customer Details")

with st.form("customer_details_form"):
    tenure = st.number_input(
        "Tenure (months)",
        min_value=0,
        max_value=72,
        value=12
    )

    monthly_charges = st.number_input(
        "Monthly Charges ($)",
        min_value=0.0,
        max_value=200.0,
        value=70.0
    )

    total_charges = st.number_input(
        "Total Charges ($)",
        min_value=0.0,
        max_value=10000.0,
        value=840.0
    )

    senior_citizen = st.selectbox("Senior Citizen", [0, 1])

    gender = st.selectbox("Gender", ["Female", "Male"])
    partner = st.selectbox("Partner", ["Yes", "No"])
    dependents = st.selectbox("Dependents", ["Yes", "No"])
    phone_service = st.selectbox("Phone Service", ["Yes", "No"])
    multiple_lines = st.selectbox(
        "Multiple Lines",
        ["No", "Yes", "No phone service"]
    )

    internet_service = st.selectbox(
        "Internet Service",
        ["DSL", "Fiber optic", "No"]
    )

    online_security = st.selectbox(
        "Online Security",
        ["Yes", "No", "No internet service"]
    )
    online_backup = st.selectbox(
        "Online Backup",
        ["Yes", "No", "No internet service"]
    )
    device_protection = st.selectbox(
        "Device Protection",
        ["Yes", "No", "No internet service"]
    )
    tech_support = st.selectbox(
        "Tech Support",
        ["Yes", "No", "No internet service"]
    )
    streaming_tv = st.selectbox(
        "Streaming TV",
        ["Yes", "No", "No internet service"]
    )
    streaming_movies = st.selectbox(
        "Streaming Movies",
        ["Yes", "No", "No internet service"]
    )

    contract = st.selectbox(
        "Contract",
        ["Month-to-month", "One year", "Two year"]
    )
    paperless_billing = st.selectbox(
        "Paperless Billing",
        ["Yes", "No"]
    )
    payment_method = st.selectbox(
        "Payment Method",
        [
            "Electronic check",
            "Mailed check",
            "Bank transfer (automatic)",
            "Credit card (automatic)"
        ]
    )

    submitted = st.form_submit_button("Predict Churn Risk")

Appending to app.py

In [68]:
# Add the prediction logic

%%writefile -a app.py

if submitted:
    customer_data = pd.DataFrame([{
        "gender": gender,
        "SeniorCitizen": senior_citizen,
        "Partner": partner,
        "Dependents": dependents,
        "tenure": tenure,
        "PhoneService": phone_service,
        "MultipleLines": multiple_lines,
        "InternetService": internet_service,
        "OnlineSecurity": online_security,
        "OnlineBackup": online_backup,
        "DeviceProtection": device_protection,
        "TechSupport": tech_support,
        "StreamingTV": streaming_tv,
        "StreamingMovies": streaming_movies,
        "Contract": contract,
        "PaperlessBilling": paperless_billing,
        "PaymentMethod": payment_method,
        "MonthlyCharges": monthly_charges,
        "TotalCharges": total_charges
    }])

    customer_data = customer_data[
        numerical_columns + categorical_columns
    ]

    customer_processed = preprocessor.transform(customer_data)

    churn_probability = model.predict_proba(customer_processed)[0, 1]
    churn_prediction = int(churn_probability >= threshold)

    st.subheader("Prediction Result")
    st.metric("Churn Probability", f"{churn_probability:.1%}")

    if churn_prediction == 1:
        st.error("High Risk: This customer is predicted to churn.")
    else:
        st.success("Lower Risk: This customer is predicted not to churn.")

    st.caption(
        f"Classification threshold: {threshold:.0%}. "
        "This prediction is an estimate, not a guarantee."
    )

Appending to app.py

In [69]:
# Verify app.py

with open("app.py", "r") as file:
    app_code = file.read()

print("Application file exists:", len(app_code) > 0)
print("Total lines:", len(app_code.splitlines()))
print("Model loading included:", 'joblib.load("customer_churn_model.joblib")' in app_code)
print("Customer form included:", 'st.form("customer_details_form")' in app_code)
print("Prediction logic included:", "model.predict_proba" in app_code)
print("Threshold logic included:", "churn_probability >= threshold" in app_code)

compile(app_code, "app.py", "exec")
print("\nSyntax check passed!")

Application file exists: True
Total lines: 153
Model loading included: True
Customer form included: True
Prediction logic included: True
Threshold logic included: True

Syntax check passed!

In [70]:
%pip install -q streamlit

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 49.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 64.0 MB/s eta 0:00:00

In [71]:
# Start the Streamlit server
import subprocess
import time
import requests

streamlit_process = subprocess.Popen(
    [
        "streamlit", "run", "app.py",
        "--server.port", "8501",
        "--server.address", "0.0.0.0",
        "--server.headless", "true"
    ],
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL
)

time.sleep(5)

try:
    response = requests.get("http://127.0.0.1:8501", timeout=10)
    print("Streamlit server status:", response.status_code)
    print("Application server is running.")
except requests.RequestException as error:
    print("Could not verify the server:", error)

Could not verify the server: HTTPConnectionPool(host='127.0.0.1', port=8501): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c36bf0af0e0>: Failed to establish a new connection: [Errno 111] Connection refused'))

In [72]:
import sklearn

print("Training scikit-learn version:", sklearn.__version__)

Training scikit-learn version: 1.6.1